logdir: ../../../logs/vanilla_gan/mnist/debug

generator_params:
  latent_dim: 128
  upsampling: deconv
  normalization: batch
  nb_filter: 64

discriminator_params:
  normalization: batch
  nb_filter: 64

solver_params:
  lr_g: 0.001
  lr_d: 0.00001

fit_params:
  batch_size: 64
  nb_epoch: 100
  save_steps: 100