logdir: ../../../logs/pggan/anime/debug
records:
  - /home/nakatsuka/workspace/dataset/safebooru/safebooru.tfrecord

generator_params:
  latent_dim: 512
  upsampling: up
  normalization: pixel

discriminator_params:
  normalization: instance
  downsampling: avg_pool

solver_params:
  lr_g: 0.001
  lr_d: 0.003
  nb_growing: 7

fit_params:
  batch_size:
    - 512
    - 256
    - 128
    - 64
    - 32
    - 16
    - 8
  nb_epoch:
    - 10
    - 20
    - 30
    - 30
    - 40
    - 40
    - 50
  nb_visualize:
    - 256
    - 256
    - 64
    - 64
    - 64
    - 64
    - 16

  save_steps: 10
  visualize_steps: 1
